### ISSUE TITLE
上传数据库备份文件时出现未定义的变量错误

### ISSUE THREAD

**Issue by jamiesun** [talkincode/ToughRADIUS#100]
![image](https://cloud.githubusercontent.com/assets/377938/16028135/b79ead92-320e-11e6-8a79-0fbc43a7f71e.png)

![image](https://cloud.githubusercontent.com/assets/377938/16028143/c7d70c68-320e-11e6-8d1c-36de04175fe4.png)

**Comment by geosson** [comment]
已经修复

**Comment by geosson** [comment]
版本1中使用的是vlan_id, vlan_id2 版本2中是vlan_id1, vlan_id2,  此处会报未定义变量错误

**Comment by tianxingxc** [comment]
基类引发的
