### ISSUE TITLE
修改管理员密码要验证原密码

### ISSUE THREAD

**Issue by lanyeit** [talkincode/ToughRADIUS#103]
![qq 20160629142531](https://cloud.githubusercontent.com/assets/16378851/16442562/005fed5e-3e06-11e6-9cfc-9640bddf1e61.png)

**Comment by jamiesun** [comment]
可以考虑

**Comment by lanyeit** [comment]
------------------ 原始邮件 ------------------
发件人: "jamiesun"; 
发送时间: 2016年6月29日(星期三) 下午2:35
收件人: "talkincode/ToughRADIUS"; 
抄送: "lanyeit"; "Author"; 
主题: Re: [talkincode/ToughRADIUS] 修改管理员密码要验证原密码 (#103)

 
可以考虑
