### ISSUE TITLE
提前生成账号或充值卡第一次登陆开始计费

### ISSUE THREAD

**Issue by lanyeit** [talkincode/ToughRADIUS#104]
生成账号有有效期，有效期内每一次登陆开始计费.

**Comment by jamiesun** [comment]
这需求很坑爹。

**Comment by lanyeit** [comment]
------------------ 原始邮件 ------------------
发件人: "jamiesun"; 
发送时间: 2016年6月29日(星期三) 晚上10:48
收件人: "talkincode/ToughRADIUS"; 
抄送: "lanyeit"; "Author"; 
主题: Re: [talkincode/ToughRADIUS] 提前生成账号或充值卡第一次登陆开始计费 (#104)

 
这需求很坑爹。
