### ISSUE TITLE
构建Jar后运行失败

### ISSUE THREAD

**Issue by LXGMAX** [talkincode/ToughRADIUS#113]
尝试CentOS/Ubuntu编译jar，CentOS 7/Ubuntu 18.04 /Windows 1809均不能运行
日志如下
[toughradius.2019-05-29.log](https://github.com/talkincode/ToughRADIUS/files/3235437/toughradius.2019-05-29.log)

**Comment by jamiesun** [comment]
使用最新的版本，这是一个读取证书路径的BUG，已经修复
