### ISSUE TITLE
设备发送认证报文服务器无响应

### ISSUE THREAD

**Issue by luxin88** [talkincode/ToughRADIUS#117]
华为的交换机，调试802.1x认证，使用test-aaa命令进行测试，ToughRADIUS有认证成功响应，实际使用中无响应，具体抓包如下：

使用test-aaa 进行测试：
![image](https://user-images.githubusercontent.com/874056/69133444-da5a4800-0af0-11ea-9030-f89479d7609c.png)

实际使用中进行认证：
![image](https://user-images.githubusercontent.com/874056/69133537-0675c900-0af1-11ea-8852-9d0a6e6f3755.png)

可见实际使用中ToughRADIUS没有响应Access-Accept报文，不知是什么原因？

**Comment by jamiesun** [comment]
这个报文是在设备还是在radius服务器抓的
认证时有没有看过radius 后台日志

**Comment by jamiesun** [comment]
使用了EAP的认证, 不支持导致的无响应
