### ISSUE TITLE
小白请问一下toughradius-latest.jar这个文件是需要自己生成吗？没有看到release里有

### ISSUE THREAD

**Issue by msghost** [talkincode/ToughRADIUS#118]
小白请问一下toughradius-latest.jar这个文件是需要自己生成吗？没有看到release里有

而脚本里都调用了这个文件

**Comment by luxin88** [comment]
用maven编译一下然后再打包

```
$mvn complie
$mvn package
```

**Comment by LXGMAX** [comment]
release只提供源码，jar需要自己用maven编译打包

**Comment by msghost** [comment]
谢谢楼上几位的解答，不会java故有此问。
我找会java的朋友试试
