### ISSUE TITLE
使用JDK11报错

### ISSUE THREAD

**Issue by luxin88** [talkincode/ToughRADIUS#119]
2019-11-20 17:14:29.514 TOUGHRADIUS [main] INFO  - Root WebApplicationContext: initialization completed in 4044 ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (jar:file:/opt/toughradius-latest.jar!/BOOT-INF/lib/mybatis-3.4.6.jar!/) to method java.lang.Class.checkPackageAccess(java.lang.SecurityManager,java.lang.ClassLoader,boolean)
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jamiesun** [comment]
11版本太高，用8
