### ISSUE TITLE
H3C MacAddr 解析失败

### ISSUE THREAD

**Issue by whl51210213** [talkincode/ToughRADIUS#120]
当设备厂商选择为H3C时，后端提示H3C MacAddr 解析失败
Vendor-Specific: H3C (25506)H3C-Ip-Host-Addr: 10.40.94.5 28:a0:2b:XX:XX:XX, 
计费start请求中”H3C-Ip-Host-Addr“字段中有已包含终端信息。
设备端的debug信息中也是有的
Acct-Session-Time=2880
Acct-Input-Octets=587786
Acct-Output-Octets=7341485
Acct-Input-Packets=5004
Acct-Output-Packets=6067
Acct-Input-Gigawords=0
Acct-Output-Gigawords=0
H3c-Ip-Host-Addr="10.40.94.2 28:a0:2b:XX:XX:XX"

**Comment by jamiesun** [comment]
H3C MAc确实需要从私有属性解析的

**Comment by jamiesun** [comment]
问题已修复, 原因是H3C在解析时属性定义多了一个空格导致解析失败
