### ISSUE TITLE
radius 字典再提交两个字段

### ISSUE THREAD

**Issue by whl51210213** [talkincode/ToughRADIUS#121]
#V7设备提示 认证处理失败 unknown attribute type 补充后实现
VENDORATTR	25506  H3C-Input-Peak-Rate			1	integer
VENDORATTR	25506  H3C-Input-Average-Rate			2	integer
VENDORATTR	25506  H3C-Input-Basic-Rate			3	integer
VENDORATTR	25506  H3C-Output-Peak-Rate			4	integer
VENDORATTR	25506  H3C-Output-Average-Rate			5	integer
VENDORATTR	25506  H3C-Output-Basic-Rate			6	integer

**Comment by jamiesun** [comment]
多谢，可以加入
