### ISSUE TITLE
请问是否支持SoftEther的radius认证？

### ISSUE THREAD

**Issue by wmailn** [talkincode/toughradius#129]
请教下，是否支持SoftEther的radius认证？
可不可以多管理多服务器？

**Comment by PaienNate** [comment]
> 请教下，是否支持SoftEther的radius认证？ 可不可以多管理多服务器？

我正在折腾这个，目前我折腾的结果是可以验证，但是好像仅限于验证，没有别的功能。现在我正在思考着怎么弄一个注册平台注册账号用，因为我对前端那个portal一点都不熟……
