### ISSUE TITLE
unauthorized access to device

### ISSUE THREAD

**Issue by xiayz** [talkincode/toughradius#146]
[2023-06-25T23:55:00+08:00]     ERROR   toughradius/radius_auth.go:29   radius auth error       {"error": "unauthorized access to device, Ip=10.211.55.2, Identifier=this.is.my.nas-identifier.de, record not found", "namespace": "radius", "metrics": "radus_auth_drop"}

use tinyradius

version: "3"
services:
  toughradius:
    image: ca17/toughradius:latest-amd64
    container_name: "toughradius"
    restart: always
    ports:
      - "1816:1816"
      - "1818:1818"
      - "1819:1819"
      - "2083:2083"
      - "11812:1812/udp"
      - "11813:1813/udp"
      - "1914:1914/udp"
    volumes:
      - /data/toughradius/data:/var/toughradius
    environment:
      - GODEBUG=x509ignoreCN=0
      - TOUGHRADIUS_SYSTEM_DEBUG=on
      - TOUGHRADIUS_DB_HOST=10.211.55.15
      - TOUGHRADIUS_DB_PORT=15432
      - TOUGHRADIUS_DB_NAME=toughradius
      - TOUGHRADIUS_DB_USER=toughradius
      - TOUGHRADIUS_DB_PWD=toughradius
      - TOUGHRADIUS_RADIUS_DEBUG=on
      - TOUGHRADIUS_RADIUS_ENABLED=on
      - TOUGHRADIUS_TR069_WEB_TLS=on
      - TOUGHRADIUS_LOKI_ENABLE=false
      - TOUGHRADIUS_LOGGER_MODE=production
      - TOUGHRADIUS_LOGGER_FILE_ENABLE=true

**Comment by jamiesun** [comment]
You need to create a vpe device, set the ip to 10.211.55.2, or the Identifier to this.is.my.nas-identifier.de

**Comment by xiayz** [comment]
请问有微信，QQ，或者群什么的，方便沟通交流。
我这怀疑是密码不一致。

**Comment by jamiesun** [comment]
@xiayz  加微信  ts6583805
