### ISSUE TITLE
太难搭建了，用docker 也不成功！

### ISSUE THREAD

**Issue by v808comd** [talkincode/toughradius#148]
用docker搭建缺少 ca17/toughradius 镜像，这个镜像无法拉取。。。
用 talkincode/toughradius 镜像替换，却只能打开web界面，用户名密码是什么也不知道，根本进不去。
还没有详细教程，全靠碰运气太苦恼了！

**Comment by jamiesun** [comment]
抱歉， 有些错误，正确的是 talkincode/toughradius ， 我觉得问题可能难在 pg 数据库容器的创建， pg 镜像有好几个版本， 很容易遇到容器挂载目录没有权限的问题， 这种情况需要手工对挂载目录设置权限。

**Comment by jamiesun** [comment]
默认用户名密码是  admin  toughradius

**Comment by jamiesun** [comment]
https://github.com/talkincode/toughradius/blob/main/docker-compose.yml

修正了两个错误， 镜像名称错误， 和数据库 host 环境变量错误

**Comment by swimmingchar** [comment]
> 默认用户名密码是 admin toughradius

这个用户名密码登陆的时候报User does not exist 是啥问题？

**Comment by swimmingchar** [comment]
首先，感觉大佬的好东东，请问一下 pg_hba.conf 这个配置文件里怎么编辑连接方式？

**Comment by swimmingchar** [comment]
感谢大佬本人搭建成功哈，主要是数据库版本问题，起来后需要再次初始化一下数据库就好了，顺便问一下字体咋搞？

**Comment by v808comd** [comment]
@jamiesun 搭建成功，感谢，但是没有发现有财务统计。是我没有找到吗？
还有，也没有发现有时间套餐，比如。1年或一个月的套餐。只能在开户的时候选择到期日期吗？

**Comment by v808comd** [comment]
@jamiesun 能加下您的QQ吗

**Comment by jamiesun** [comment]
您可以加我微信 ts6583805， 目前这个版本只是提供认证记账功能，并没有提供财务功能

**Comment by uepuer** [comment]
请问dockerc-ompose.yml 搭建成功之后的，登录账号与密码什么呀！ admin/toughradius  登录 不上啊！页在刷新一下，又回到登录页面了，又也不报错，不清楚 什么情况

**Comment by sagezhj** [comment]
> 感谢大佬本人搭建成功哈，主要是数据库版本问题，起来后需要再次初始化一下数据库就好了，顺便问一下字体咋搞？

请问如何初始化数据库，好像没看到相关说明？

**Comment by jamiesun** [comment]
第一次会自动初始化建表，前提是要正常连接到数据库
