### ISSUE TITLE
Import user template

### ISSUE THREAD

**Issue by yukwang** [talkincode/ToughRADIUS#18]
应提供一个用户导入模板方便用户的导入，鉴于使用了用户和账号双层的id，应对各层id的密码和导入时将选择的套餐类型予以说明，避免将用户导入至错误的套餐内。
若已经在rm上有用户，可否提供一个将rm中缴费历史导入进来的方法。

**Comment by yankaiqian** [comment]
我也有个和用户导入有关问题，首先说明下情况：

* DB是用的0.9.1时创建的，管理系统升级到了0.9.3，不知道到是否会有兼容问题；
* 系统中已经有一个用户，姓名为：yanqian；

我在0.9.3管理界面使用用户数据导入的功能，数据内容如下：

    yanqian,test01,passwd01,2015-12-30,0,0,0
    yanqian,test02,passwd01,2015-12-30,0,0,0

导入后发现系统新建了两个同名用户“yanqian”，这样就有三个“yanqian”了，我原本期望的效果是将test01、test02导入到原先的那个“yanqian”下面。
