### ISSUE TITLE
Got error message when ToughRADIUS server had a network issue

### ISSUE THREAD

**Issue by yankaiqian** [talkincode/ToughRADIUS#21]
I installed 0.9.1 on CentOS 6.6 in vmware.

When I change the VMware NAT(port forwarding) settings, Admin Web page will fail to work, it shows error messages as below:

"出错了!

Server Internal error Can't reconnect until invalid transaction is rolled back (original cause: InvalidRequestError: Can't reconnect until invalid transaction is rolled back) u'SELECT  slc_param.param_value AS slc_param_param_value \nFROM slc_param \nWHERE slc_param.param_name = %s' [immutabledict({})]"

I have to press Ctrl+C stop "toughctl --admin", and then start it again.
As I know, when change the (VMware) NAT settings, the network connection of guest OS will disconnect for a little moment, that is the cause of the failed error.

**Comment by jamiesun** [comment]
多谢反馈，我会检查下这个问题

**Comment by yankaiqian** [comment]
最近发现这个问题还挺频繁遇到的，我的ToughRadius（TR）是跑在VM虚拟机里面，但是DB是用的另一台现成的mysql server，可能是TR和DB不在同一台上时这个问题会更容易发生。

**Comment by jamiesun** [comment]
l现在做了一个连接定期回收的机制，应该解决了问题

**Comment by yankaiqian** [comment]
谢谢！
我觉得应该是解决了，可以先close这个issue，我也再观察看看。
