### ISSUE TITLE
添加操作员时如果密码含有@字符提交会报错

### ISSUE THREAD

**Issue by yankaiqian** [talkincode/ToughRADIUS#25]
报错内容为：

>出错了!
Server Internal error argument of type 'Undefined' is not iterable

使用不带@字符的密码就正常。

**Comment by jamiesun** [comment]
验证表单的表达式出了问题

**Comment by yankaiqian** [comment]
嗯，刚才试了下，含有下划线（_）也不行。

**Comment by jamiesun** [comment]
搞错了，不是格式错误，是少了变量
