### ISSUE TITLE
0.9.8的Windows版本admin log路径设置无效

### ISSUE THREAD

**Issue by yankaiqian** [talkincode/ToughRADIUS#33]
我测试了下0.9.8的windows版本（在Windows 2008 R2上），发现radiusd、admin、customer的log默认都是写到了logs/radiusd.log。

实际上后两者的log按照默认设置应该分别写到logs/admin.log、logs/customer.log才对。

**Comment by jamiesun** [comment]
是这样的，目前强制写到一个日志了，全局只有一个日志记录器
