### ISSUE TITLE
新建的操作员更改密码后导致admin账号密码被改

### ISSUE THREAD

**Issue by yankaiqian** [talkincode/ToughRADIUS#35]
版本：1.0.0
使用新建操作员登入，点击页面顶部“修改密码”，自己密码并没有改变，修改的反而是admin账号的密码。

我觉得这个修改密码功能应该是修改当前（操作员）登入账号的密码才对。

**Comment by jamiesun** [comment]
确认修改界面显示的是admin吗

**Comment by yankaiqian** [comment]
修改密码界面有三个栏位，第一个“管理员名”灰色，显示的就是当前登入的账号（非admin），输入“管理员新密码”、“确认管理员新密码”，点击更新后，admin密码被更新了，当前账号的密码反而没变。

    管理员名  
    管理员新密码
    确认管理员新密码
