### ISSUE TITLE
管理员可不可以也分组

### ISSUE THREAD

**Issue by piaofeng0129** [talkincode/ToughRADIUS#56]
管理员可不可以也分组  比如 管理员  主管 经理  还有 离职人员

**Comment by dengweiwei** [comment]
你好，
  目前ToughRADIU不支持权限组、权限组与操作员关联功能，如果需要，可以基于ToughRADIUS定制开发













----------------------------------------
湖南硬派科技有限公司: 邓微（销售顾问）
手机: 18774997822
地址: 湖南省长沙经济开发区东四路与特立路交汇处

 

 
 
 
------------------ Original ------------------

**Comment by yankaiqian** [comment]
我也追问一个，“备份管理”的功能可否也列入操作员权限设定选项中？

**Comment by dengweiwei** [comment]
可以的，TR的权限控制设计是基于控制菜单栏目的
------------------ Original ------------------

**Comment by yankaiqian** [comment]
了解了，我还停留在1.0.x版本。

原来新版中备份管理的功能已经换地方了，刚看到1.1.5的更新说明中有：

“数据库备份管理功能迁移到系统控制管理界面，新增上传数据恢复功能，数据库初始化功能。”

**Comment by dengweiwei** [comment]
感谢你对TR的关注与支持，谢谢！ 
------------------ Original ------------------
