### ISSUE TITLE
是否支持NAS绑定

### ISSUE THREAD

**Issue by cuibty** [talkincode/ToughRADIUS#57]

**Comment by dengweiwei** [comment]
你好!
  请问你所指的绑定是需要绑定哪些？NAS绑定的范围很大的如：区域、IP等等











----------------------------------------
湖南硬派科技有限公司: 邓微（销售顾问）
手机: 18774997822
地址: 湖南省长沙经济开发区东四路与特立路交汇处

 

 
 
 
------------------ Original ------------------
