### ISSUE TITLE
After User register. User is not show in admin member 

### ISSUE THREAD

**Issue by sumonchai** [talkincode/ToughRADIUS#58]
![2015-07-25_012748](https://cloud.githubusercontent.com/assets/5920739/8881793/a857d1b2-326c-11e5-8429-bbb25bd9d9db.png)
 User register and access

![2015-07-25_012819](https://cloud.githubusercontent.com/assets/5920739/8881802/b95eb0ca-326c-11e5-9ffc-6cdbb859ceec.png)
Member register not show in admin

**Comment by tianxingxc** [comment]
自助开通的用户需要激活(在系统管理的参数设置中设置可用的邮件服务器信息：如smtp服务器)，自助开通用户输入的邮件地址必须可用来接受邮件，有些smtp服务器会拦截邮件报535等错误，推荐使用qq的（测试可用），接收到系统发出的激活邮件后，如
http://forum.toughradius.net/active/BEB2EDAE32DB11E58808A45E60EA5A4F，修改
／active前的地址改为你radius服务器的地址加端口1817，激活完成，此时用户已经激活，但是用户信息中还是不会显示，下一步操作：用户自助开通，具体如下：在管理系统中生成充值卡，激活充值卡。。。，再在用户自助系统中操作用户自助开户，完成后就可以显示用户信息了。

**Comment by sumonchai** [comment]
thak a lot

**Comment by jamiesun** [comment]
没有上网账号的会员不会显示，不过这个确实有些其他小问题

**Comment by dengweiwei** [comment]
感谢你对TR的关注，关于你的问题能提供详细点的说明吗？  可以加QQ群 464025428
------------------ Original ------------------
