### ISSUE TITLE
是否支持PPTP等接入？

### ISSUE THREAD

**Issue by towserchen** [talkincode/ToughRADIUS#59]
比如 freeradius-client 配合 PPTP 最终使用 ToughRAIDUS 认证？

**Comment by dengweiwei** [comment]
支持。 
------------------ Original ------------------

**Comment by dengweiwei** [comment]
可以支持的 若还有其他问题可以加 技术支持QQ群: 464025428













----------------------------------------
湖南硬派科技有限公司: 邓微（销售经理）
手机: 18774997822
地址: 湖南省长沙经济开发区东四路与特立路交汇处

 

 
 
 
------------------ Original ------------------
