### ISSUE TITLE
绑定VLAN没有生效

### ISSUE THREAD

**Issue by chinabb** [talkincode/ToughRADIUS#60]
老大，计费策略设置了绑定VLAN，用户也是绑定VLAN及MAC的，拨号后，查看VLAN1、2还是0/0，手动修改数据库中的VLAN_ID/VLAN_ID2为QINQ的两个VLAN，无论怎么改，还是可以拨号，请教如何可以绑定QINQ的VLAN呢？谢谢！

**Comment by jamiesun** [comment]
应该是vlan解析失败的问题

**Comment by jamiesun** [comment]
可以提交抓包文件来分析一下

**Comment by chinabb** [comment]
嗯，是没解析到VLAN信息，QINQ的问题，谢谢！
