### ISSUE TITLE
PPTP与ToughRDIUS对接后无法使用MPPE

### ISSUE THREAD

**Issue by syxoasis** [talkincode/ToughRADIUS#65]
当PPTP启动MPPE时，PPTP服务器提示

Dec  9 07:36:27 rdqd1 pppd[17910]: Unsupported protocol 0xc7 received
Dec  9 07:36:27 rdqd1 pppd[17910]: Unsupported protocol 0x11 received
Dec  9 07:36:27 rdqd1 pppd[17910]: Unsupported protocol 0xcb received
Dec  9 07:36:28 rdqd1 pppd[17910]: Unsupported protocol 'AppleTalk SmartBuffered' (0x3b) received
Dec  9 07:36:28 rdqd1 pppd[17910]: Unsupported protocol 0xc88 received
Dec  9 07:36:28 rdqd1 pppd[17910]: Unsupported protocol 0x7021 received

关闭MPPE则正常，我需要启用MPPE，请问应该如何配置？

**Comment by jamiesun** [comment]
#66
