### ISSUE TITLE
关于mysql配置后会被自动删除的问题

### ISSUE THREAD

**Issue by lost404** [talkincode/ToughRADIUS#75]
你好，我在配置mysql时遇到这样一个问题。
我配置mysql时，能够正常连接（我没有使用docker的mysql，用的微林的云mysql），配置好后重启所有服务，然后初始化，这些都能够成功，而且所有的数据表等都已正常建立。
当我添加BCS、资费信息、用户之后，目前还是正常。
当我尝试用客户端连接pptp时，无法正常连接，之前是按配置来的，应该不会出错，然后去刷新管理界面，显示mysql错误，没有表（online这张，应该是统计用户在线情况的，具体叫什么名字我想不起来了，因为我重装系统，删除数据库了），我重复重装数据库，按上面步骤添加各项，可是一连接这个表就被删除了，我尝试找这段源码，没有找到，不清楚具体是怎么回事儿？

**Comment by jamiesun** [comment]
online表是一个内存表，不知道是不是采用的mysql版本不一样的问题。

toughradius在第一次创建容器实例的时候会自动创建表，包括online内存表，如果重装了数据库，最好初始化一次

**Comment by lost404** [comment]
初始化过，可是还是一样的，尝试登陆过后就自动删除了
