### ISSUE TITLE
输出的syslog格式不符合标准

### ISSUE THREAD

**Issue by yankaiqian** [talkincode/ToughRADIUS#89]
TR的syslog格式是这样：
Apr  3 06:22:44 toughradius_admin toughstruct INFO     start process expire_notify task

而linux系统默认的格式是：
Mar 27 20:45:01 PSH-PX-04 squid[17748]: Squid Parent: child process 17750 started

具体可以参考RFC标准，大概是：<PRI>TIMESTAMP HOSTNAME MESSAGE
facility和level都是在最前面的<PRI>值中，后面的MESSAGE又包括程序名称、程序ID、具体内容等。

**Comment by toughmen** [comment]
MESSAGE没有做详细的切分
