### ISSUE TITLE
短信功能支持

### ISSUE THREAD

**Issue by jamiesun** [talkincode/ToughRADIUS#9]
自助服务短信验证
到期短信提醒
监控短信告警

**Comment by yukwang** [comment]
临期短信提醒（通过系统设置临期提醒时间，当账号的expiration-当前时间小于提醒时间时执行临期提醒发送，可定义发送频率，比如1天，2天。定义发送的时间。）
自定义短信内容（根据不同的区域定制不同的短信提醒字段，比如：欢迎使用xxx，您的帐户已启用）
和各短信平台的对接方法（各短信平台都有对接的api）

**Comment by jamiesun** [comment]
短信这个功能还真不好做，到达率是个问题，平台选择是个问题。所以决定放弃这个功能，但是也提供另一个应该说是更好的选择。

系统提供一个用户可自定义参数的通知url，系统定时触发，使用客户自己去完成这个url后端的实现，可以用第三方的，可以自己做。
