### ISSUE TITLE
增加Mikrotik-Xmit-Limit支持

### ISSUE THREAD

**Issue by fillorkill** [talkincode/ToughRADIUS#95]
目前貌似并不支持
RadiusError:current radius cannot support attribute Mikrotik-Xmit-Limit,Can not encode non-integer(10000000) as integer

**Comment by jamiesun** [comment]
这是哪里出现的提示

**Comment by fillorkill** [comment]
authenticate accept之后

修改radiusd.py: 在 # todo: May have a type matching problem下面，修改为：
for attr_name in attrs:
                    try:
                        # todo: May have a type matching problem
                        if utils.safestr(attr_name) == "Mikrotik-Xmit-Limit":
                                reply.AddAttribute(utils.safestr(attr_name), int(auth_resp['flow_length'])*1024)
                        else:
                                reply.AddAttribute(utils.safestr(attr_name), attrs[attr_name])
                    except Exception as err:
                        errstr = "RadiusError:current radius cannot support attribute {0},{1}".format(
                            attr_name,utils.safestr(err.message))
                        logger.error(errstr)

同时需在radius_authorize.py中def policy_filter最后添加
        self.reply['flow_length'] = self.get_user_flow_length()
这样可以实现Mikrotik-Xmit-Limit流量计费，自动断开功能。

**Comment by jamiesun** [comment]
了解，你是说反向下发流量数据给ros，让ros控制，但是如果用户充值了呢，那还得去动态授权更新这个数据。

**Comment by jamiesun** [comment]
最好用一个插件去控制，比如速率

    if u"input_rate" in auth_resp and u"output_rate" in auth_resp:
        reply = rate_process.process(reply, input_rate=auth_resp['input_rate'], output_rate=auth_resp['output_rate'])

**Comment by yankaiqian** [comment]
我测试 v2.1.10 也遇到一样的问题，就是资费套餐里面添加扩展策略属性（比如限速相关的）时会看到认证log中有报错。
不过这个版本是比较老了。

> [Jul 23 13:00:16 toughradius] <RadiusError> TypeError('Can not encode non-integer(3072000) as integer',) 'RadiusError:current radius cannot support attribute WISPr-Bandwidth-Max-Down,Can not encode non-integer(3072000) as integer'
[Jul 23 13:00:16 toughradius] <RadiusError> TypeError('Can not encode non-integer(1024000) as integer',) 'RadiusError:current radius cannot support attribute WISPr-Bandwidth-Max-Up,Can not encode non-integer(1024000) as integer'
